export const FETCH_USERS = 'MY-TEST/FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'MY-TEST/FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'MY-TEST/FETCH_USERS_FAILURE'

export const DELETE_USER = 'MY-TEST/DELETE_USER'
export const DELETE_USER_SUCCESS = 'MY-TEST/DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'MY-TEST/DELETE_USER_FAILURE'

export const CREATE_USER = 'MY-TEST/CREATE_USER'
export const CREATE_USER_SUCCESS = 'MY-TEST/CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'MY-TEST/CREATE_USER_FAILURE'

export const UPDATE_USER = 'MY-TEST/UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'MY-TEST/UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'MY-TEST/UPDATE_USER_FAILURE'

export const FETCH_FILTER = 'MY-TEST/FETCH_FILTER'
export const FETCH_FILTER_USERS_SUCCESS = 'MY-TEST/FETCH_FILTER_USERS_SUCCESS'
export const FETCH_FILTER_USERS_FAILURE = 'MY-TEST/FETCH_FILTER_USERS_FAILURE'




